name: Build LeechCore

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild LeechCore.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: leechcore-build
          path: |
            **/leechcore.dll
            **/libleechgrpc.dll
            **/leechcore_device_*.dll
